version: '3.8'

services:
  frontend:
     build:
      context: ./frontend
      dockerfile: Dockerfile
     ports:
      - 8000:8000
     container_name: frontend
     networks:
       -  mean-stack-net
     volumes:
       -  ./frontend/src:/usr/app/src
       -  ./frontend/public:/usr/app/public 
     depends_on:
      - backend
      
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: backend
    networks:
       -  mean-stack-net
    volumes:
       -  ./backend/controllers:/usr/app/controllers
       -  ./backend/db:/usr/app/db
       -  ./backend/models:/usr/app/models
       -  ./backend/routes:/usr/app/routes    
    depends_on:
      - mongodb
      
  mongodb:
    image: mongo:4
    ports:
      - 27017:27017
    container_name: mongodb
    networks:
      - mean-stack-net
    volumes:
      - mongo-data:/data/db

networks:
  mean-stack-net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
