version: '3.8'

services:
  frontend:
     build:
      context: ./frontend
      dockerfile: Dockerfile
     ports:
      - "3000:3000"
     depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
  mongodb:
    image: mongo:4
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=movies-app
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
