version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"    
    depends_on:
      - db
  backend: 
    build: ./backend
    ports: 
      - "9000:9000"    #external:internal 
    depends_on:
      - db
  db:
    volumes:
      - slack_db:/data/db
    image: mongo:latest
    ports:
      - "27017:27017"  
    volumes:
      - /home/rayudu/mango-backup:data/db
volumes:
